### ISSUE TITLE
Unable to download server maps

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#247]
I cannot play '_christmas_dutility' on The Shire, also people couldn't play on the old version of echo I have on my server 'echo1k' which both I and the server have, even after /getmap.

This is on the stable branch of both client and server.

**Comment by qreeves** [comment]
Fixed.

**Comment by shirepirate** [comment]
i'm still having this issue on some maps, only specific maps. some maps are fine, others say "no-one has a copy of this map" every time, when the server clearly has a copy.

does it have something to do with the map file being older?

**Comment by qreeves** [comment]
Maybe grab the demo next time (if you want to speed it up, `timelimit 1; overtimeallow 0`).

**Comment by shirepirate** [comment]
don't know of a way to post a demo here, but there's nothing to show on it anyway. the map is never loaded. the issue happens every time with specific maps, though.

if you want to test connect to **68.58.164.95:[28801]** and try the maps _gecility or _christmas_dutility

other older maps will fetch just fine with /getmap, but these will not.

**Comment by shacknetisp** [comment]
I have seen several times where on my editing server people can't get the map even if someone runs /sendmap and the player without the map does /getmap

**Comment by shirepirate** [comment]
some people have experienced lately not being able to download the map when joining edit mode (once again, only on specific maps). even when other players /sendmap and the one experiencing the problem tries /getmap again. obviously related to this

**Comment by qreeves** [comment]
This still present in `master`?

**Comment by bonifarz** [comment]
That's an important question, since `sendmap` does not exist in master, but there's a weird problem when joining edit games, #364. Though, that does not seem to be related to getting map data, does it?
